export type ArgType = "string" | "boolean";
export type BodyMode = "none" | "json" | "form" | "jsonOrForm";
export type PaginationMode = "ws" | "link";

export interface FlagDefinition {
  flag: string;
  param: string;
  type?: ArgType;
}

export interface OperationDefinition {
  group: string;
  action: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  pathTemplate: string;
  help: string;
  version?: "v1" | "beta";
  requiresAccountId?: boolean;
  requiresListId?: boolean;
  pathFlags?: FlagDefinition[];
  queryFlags?: FlagDefinition[];
  bodyFlags?: FlagDefinition[];
  fixedQuery?: Record<string, string>;
  bodyMode?: BodyMode;
  pagination?: PaginationMode;
}

const stringFlag = (flag: string, param: string): FlagDefinition => ({ flag, param, type: "string" });
const booleanFlag = (flag: string, param: string): FlagDefinition => ({ flag, param, type: "boolean" });

export const OPERATION_DEFINITIONS: OperationDefinition[] = [
  { group: "accounts", action: "list", method: "GET", pathTemplate: "/accounts", help: "aweber accounts list [--all] [--json]", pagination: "ws" },
  { group: "accounts", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}", help: "aweber accounts get [--account-id <id>] [--json]", requiresAccountId: true },
  { group: "integrations", action: "list", method: "GET", pathTemplate: "/accounts/{accountId}/integrations", help: "aweber integrations list [--account-id <id>] [--all] [--json]", requiresAccountId: true, pagination: "ws" },
  { group: "integrations", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}/integrations/{integrationId}", help: "aweber integrations get --integration-id <id> [--account-id <id>] [--json]", requiresAccountId: true, pathFlags: [stringFlag("--integration-id", "integrationId")] },
  { group: "lists", action: "list", method: "GET", pathTemplate: "/accounts/{accountId}/lists", help: "aweber lists list [--account-id <id>] [--all] [--json]", requiresAccountId: true, pagination: "ws" },
  { group: "lists", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}", help: "aweber lists get [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true },
  { group: "lists", action: "find", method: "GET", pathTemplate: "/accounts/{accountId}/lists", help: "aweber lists find [--account-id <id>] [--query name=Newsletter] [--all] [--json]", requiresAccountId: true, fixedQuery: { "ws.op": "find" }, pagination: "ws" },
  { group: "lists", action: "tags", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/tags", help: "aweber lists tags [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true },
  { group: "custom-fields", action: "list", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/custom_fields", help: "aweber custom-fields list [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pagination: "ws" },
  { group: "custom-fields", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/custom_fields/{customFieldId}", help: "aweber custom-fields get --custom-field-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--custom-field-id", "customFieldId")] },
  { group: "custom-fields", action: "create", method: "POST", pathTemplate: "/accounts/{accountId}/lists/{listId}/custom_fields", help: "aweber custom-fields create [--account-id <id>] [--list-id <id>] --form name=vip [--json]", requiresAccountId: true, requiresListId: true, bodyMode: "form" },
  { group: "custom-fields", action: "update", method: "PATCH", pathTemplate: "/accounts/{accountId}/lists/{listId}/custom_fields/{customFieldId}", help: "aweber custom-fields update --custom-field-id <id> [--account-id <id>] [--list-id <id>] --form name=vip [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--custom-field-id", "customFieldId")], bodyMode: "form" },
  { group: "custom-fields", action: "delete", method: "DELETE", pathTemplate: "/accounts/{accountId}/lists/{listId}/custom_fields/{customFieldId}", help: "aweber custom-fields delete --custom-field-id <id> [--account-id <id>] [--list-id <id>]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--custom-field-id", "customFieldId")] },
  { group: "landing-pages", action: "list", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/landing_pages", help: "aweber landing-pages list [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pagination: "ws" },
  { group: "landing-pages", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/landing_pages/{landingPageId}", help: "aweber landing-pages get --landing-page-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--landing-page-id", "landingPageId")] },
  { group: "segments", action: "list", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/segments", help: "aweber segments list [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pagination: "ws" },
  { group: "segments", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/segments/{segmentId}", help: "aweber segments get --segment-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--segment-id", "segmentId")] },
  { group: "webforms", action: "list-account", method: "GET", pathTemplate: "/accounts/{accountId}", help: "aweber webforms list-account [--account-id <id>] [--all] [--json]", requiresAccountId: true, fixedQuery: { "ws.op": "getWebForms" }, pagination: "ws" },
  { group: "webforms", action: "split-tests-account", method: "GET", pathTemplate: "/accounts/{accountId}", help: "aweber webforms split-tests-account [--account-id <id>] [--all] [--json]", requiresAccountId: true, fixedQuery: { "ws.op": "getWebFormSplitTests" }, pagination: "ws" },
  { group: "webforms", action: "list", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/web_forms", help: "aweber webforms list [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pagination: "ws" },
  { group: "webforms", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/web_forms/{webformId}", help: "aweber webforms get --webform-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--webform-id", "webformId")] },
  { group: "webforms", action: "split-tests", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/web_form_split_tests", help: "aweber webforms split-tests [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pagination: "ws" },
  { group: "webforms", action: "get-split-test", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/web_form_split_tests/{splitTestId}", help: "aweber webforms get-split-test --split-test-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--split-test-id", "splitTestId")] },
  { group: "webforms", action: "components", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/web_form_split_tests/{splitTestId}/components", help: "aweber webforms components --split-test-id <id> [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--split-test-id", "splitTestId")], pagination: "ws" },
  { group: "webforms", action: "get-component", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/web_form_split_tests/{splitTestId}/components/{splitTestComponentId}", help: "aweber webforms get-component --split-test-id <id> --split-test-component-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--split-test-id", "splitTestId"), stringFlag("--split-test-component-id", "splitTestComponentId")] },
  { group: "subscribers", action: "list", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers", help: "aweber subscribers list [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pagination: "ws", queryFlags: [stringFlag("--sort-order", "sort_order")] },
  { group: "subscribers", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers/{subscriberId}", help: "aweber subscribers get --subscriber-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--subscriber-id", "subscriberId")] },
  { group: "subscribers", action: "add", method: "POST", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers", help: "aweber subscribers add --email <email> [--account-id <id>] [--list-id <id>] [--field name='Jane'] [--json]", requiresAccountId: true, requiresListId: true, bodyMode: "jsonOrForm", bodyFlags: [stringFlag("--email", "email")] },
  { group: "subscribers", action: "update", method: "PATCH", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers", help: "aweber subscribers update --email <email> [--account-id <id>] [--list-id <id>] --field name='Jane' [--json]", requiresAccountId: true, requiresListId: true, queryFlags: [stringFlag("--email", "email")], bodyMode: "jsonOrForm" },
  { group: "subscribers", action: "delete", method: "DELETE", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers", help: "aweber subscribers delete --email <email> [--account-id <id>] [--list-id <id>]", requiresAccountId: true, requiresListId: true, queryFlags: [stringFlag("--email", "email")] },
  { group: "subscribers", action: "update-by-id", method: "PATCH", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers/{subscriberId}", help: "aweber subscribers update-by-id --subscriber-id <id> [--account-id <id>] [--list-id <id>] --field name='Jane' [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--subscriber-id", "subscriberId")], bodyMode: "jsonOrForm" },
  { group: "subscribers", action: "delete-by-id", method: "DELETE", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers/{subscriberId}", help: "aweber subscribers delete-by-id --subscriber-id <id> [--account-id <id>] [--list-id <id>]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--subscriber-id", "subscriberId")] },
  { group: "subscribers", action: "move", method: "POST", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers/{subscriberId}", help: "aweber subscribers move --subscriber-id <id> [--account-id <id>] [--list-id <id>] --form list_id=789 [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--subscriber-id", "subscriberId")], bodyMode: "form" },
  { group: "subscribers", action: "find", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers", help: "aweber subscribers find [--account-id <id>] [--list-id <id>] [--query email=user@example.com] [--all] [--json]", requiresAccountId: true, requiresListId: true, fixedQuery: { "ws.op": "find" }, pagination: "ws", queryFlags: [stringFlag("--sort-key", "sort_key"), stringFlag("--sort-order", "sort_order"), stringFlag("--ws-show", "ws.show")] },
  { group: "subscribers", action: "find-account", method: "GET", pathTemplate: "/accounts/{accountId}", help: "aweber subscribers find-account [--account-id <id>] [--query email=user@example.com] [--all] [--json]", requiresAccountId: true, fixedQuery: { "ws.op": "findSubscribers" }, pagination: "ws", queryFlags: [stringFlag("--ws-show", "ws.show")] },
  { group: "subscribers", action: "activity", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/subscribers/{subscriberId}", help: "aweber subscribers activity --subscriber-id <id> [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--subscriber-id", "subscriberId")], fixedQuery: { "ws.op": "getActivity" }, pagination: "ws" },
  { group: "subscribers", action: "purchase", method: "POST", pathTemplate: "/accounts/{accountId}/lists/{listId}/purchases", help: "aweber subscribers purchase [--account-id <id>] [--list-id <id>] --data '{\"email\":\"buyer@example.com\"}' [--json]", requiresAccountId: true, requiresListId: true, bodyMode: "json" },
  { group: "broadcasts", action: "list", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts", help: "aweber broadcasts list --status <draft|scheduled|sent> [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, queryFlags: [stringFlag("--status", "status")], pagination: "ws" },
  { group: "broadcasts", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts/{broadcastId}", help: "aweber broadcasts get --broadcast-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--broadcast-id", "broadcastId")] },
  { group: "broadcasts", action: "create", method: "POST", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts", help: "aweber broadcasts create [--account-id <id>] [--list-id <id>] --form subject='Hello' --form body_html='<p>Hi</p>' --form body_text='Hi' [--json]", requiresAccountId: true, requiresListId: true, bodyMode: "form" },
  { group: "broadcasts", action: "update", method: "PUT", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts/{broadcastId}", help: "aweber broadcasts update --broadcast-id <id> [--account-id <id>] [--list-id <id>] --form subject='Hello' [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--broadcast-id", "broadcastId")], bodyMode: "form" },
  { group: "broadcasts", action: "delete", method: "DELETE", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts/{broadcastId}", help: "aweber broadcasts delete --broadcast-id <id> [--account-id <id>] [--list-id <id>]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--broadcast-id", "broadcastId")] },
  { group: "broadcasts", action: "cancel", method: "POST", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts/{broadcastId}/cancel", help: "aweber broadcasts cancel --broadcast-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--broadcast-id", "broadcastId")] },
  { group: "broadcasts", action: "total", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts/total", help: "aweber broadcasts total --status <draft|scheduled|sent> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, queryFlags: [stringFlag("--status", "status")] },
  { group: "broadcasts", action: "schedule", method: "POST", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts/{broadcastId}/schedule", help: "aweber broadcasts schedule --broadcast-id <id> --scheduled-for <iso8601> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--broadcast-id", "broadcastId")], bodyMode: "form", bodyFlags: [stringFlag("--scheduled-for", "scheduled_for")] },
  { group: "broadcasts", action: "opens", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts/{broadcastId}/opens", help: "aweber broadcasts opens --broadcast-id <id> [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--broadcast-id", "broadcastId")], pagination: "link" },
  { group: "broadcasts", action: "clicks", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/broadcasts/{broadcastId}/clicks", help: "aweber broadcasts clicks --broadcast-id <id> [--detailed] [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--broadcast-id", "broadcastId")], queryFlags: [booleanFlag("--detailed", "detailed")], pagination: "link" },
  { group: "campaigns", action: "list", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/campaigns", help: "aweber campaigns list [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pagination: "ws" },
  { group: "campaigns", action: "get", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/campaigns/{campaignType}{campaignId}", help: "aweber campaigns get --campaign-type <b|f> --campaign-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--campaign-type", "campaignType"), stringFlag("--campaign-id", "campaignId")] },
  { group: "campaigns", action: "find", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/campaigns", help: "aweber campaigns find --campaign-type <b|f> [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, fixedQuery: { "ws.op": "find" }, queryFlags: [stringFlag("--campaign-type", "campaign_type"), stringFlag("--ws-show", "ws.show")], pagination: "ws" },
  { group: "campaigns", action: "stats", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/campaigns/b{campaignId}/stats", help: "aweber campaigns stats --campaign-id <id> [--account-id <id>] [--list-id <id>] [--all] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--campaign-id", "campaignId")], pagination: "ws" },
  { group: "campaigns", action: "stat", method: "GET", pathTemplate: "/accounts/{accountId}/lists/{listId}/campaigns/b{campaignId}/stats/{statsId}", help: "aweber campaigns stat --campaign-id <id> --stats-id <id> [--account-id <id>] [--list-id <id>] [--json]", requiresAccountId: true, requiresListId: true, pathFlags: [stringFlag("--campaign-id", "campaignId"), stringFlag("--stats-id", "statsId")] },
  { group: "analytics", action: "broadcast-links", method: "GET", pathTemplate: "/analytics/reports/broadcasts-links", help: "aweber analytics broadcast-links --account-uuid <uuid> --broadcast-uuid <uuid> --filter <clicks|pageviews> [--all] [--json]", version: "beta", queryFlags: [stringFlag("--account-uuid", "account_id"), stringFlag("--broadcast-uuid", "broadcast_id"), stringFlag("--filter", "filter"), stringFlag("--min-count", "min_count"), stringFlag("--max-count", "max_count"), stringFlag("--sort-by", "sort_by"), booleanFlag("--sort-asc", "sort_asc")], pagination: "link" },
];

export function getOperation(group: string, action: string): OperationDefinition | undefined {
  return OPERATION_DEFINITIONS.find((operation) => operation.group === group && operation.action === action);
}

export function getOperationHelp(group: string): string[] {
  return OPERATION_DEFINITIONS
    .filter((operation) => operation.group === group)
    .map((operation) => `  ${operation.help}`);
}
